// File: ram.v
// Generated by MyHDL 0.11
// Date: Tue Dec 15 00:33:49 2020


`timescale 1ns/10ps

module ram (
    clk_i,
    wr_i,
    addr_i,
    data_i,
    data_o
);


input clk_i;
input wr_i;
input [8:0] addr_i;
input [9:0] data_i;
output [9:0] data_o;
reg [9:0] data_o;

reg [9:0] mem [0:512-1];



always @(posedge clk_i) begin: RAM_LOC_INSTS_CHUNK_INSTS_K
    if (wr_i) begin
        mem[addr_i] <= data_i;
    end
    else begin
        data_o <= mem[addr_i];
    end
end

endmodule
