// File: simpler_ram.v
// Generated by MyHDL 0.11
// Date: Tue Dec 15 00:33:48 2020


`timescale 1ns/10ps

module simpler_ram (
    clk_i,
    wr_i,
    addr_i,
    data_i,
    data_o
);


input clk_i;
input wr_i;
input [7:0] addr_i;
input [7:0] data_i;
output [7:0] data_o;
reg [7:0] data_o;

reg [7:0] mem [0:256-1];



always @(posedge clk_i) begin: SIMPLER_RAM_LOC_INSTS_CHUNK_INSTS_K
    if (wr_i) begin
        mem[addr_i] <= data_i;
    end
    data_o <= mem[addr_i];
end

endmodule
